main: com.sagaciousdevelopment.PlaceholderSign.Core
name: PlaceholderSign
version: 1.0
author: Sagacious_
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
commands: 
  editsign:
   aliases: [es]
  scrollsign:
   aliases: [ss] 