main: com.sagaciousdevelopment.PlaceholderSign.Core
name: PlaceholderSign
version: 1.1
api-version: 1.13
author: Sagacious_
softdepend: [PlaceholderAPI, MVdWPlaceholderAPI]
commands: 
  editsign:
   aliases: [es]